# Generated by Django 4.0 on 2023-09-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='posts_liked',
            new_name='post_liked',
        ),
    ]
